package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Saturday, 20 April, 2024 1:32:44 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
